export {
  Tabs,
  TabsContent,
  TabsContentGroup,
  TabsIndicator,
  TabsList,
  TabsPanel,
  TabsParts,
  TabsRoot,
  TabsTab,
  TabsTrigger,
  type TabsActivationMode,
  type TabsContentGroupOwnProps,
  type TabsContentOwnProps,
  type TabsContentProps,
  type TabsIndicatorOwnProps,
  type TabsIndicatorProps,
  type TabsJustify,
  type TabsListOwnProps,
  type TabsListProps,
  type TabsRootOwnProps,
  type TabsRootProps,
  type TabsSize,
  type TabsTriggerOwnProps,
  type TabsTriggerProps,
  type TabsVariant
} from "./Tabs";
