import { defineConfig } from "tsup";

export default defineConfig({
  clean: true,
  dts: true,
  entry: [
    "src/index.ts",
    "src/styles.css",
    "src/styles/layers/base.css",
    "src/styles/layers/actions.css",
    "src/styles/layers/feedback.css",
    "src/styles/layers/forms.css",
    "src/styles/layers/overlays.css",
    "src/styles/layers/navigation.css",
    "src/styles/layers/data-display.css",
    "src/styles/layers/layout.css",
    "src/actions/button/index.ts",
    "src/actions/icon-button/index.ts",
    "src/data-display/avatar/index.ts",
    "src/data-display/card/index.ts",
    "src/data-display/data-table/index.ts",
    "src/data-display/table/index.ts",
    "src/data-display/timeline/index.ts",
    "src/feedback/alert/index.ts",
    "src/feedback/badge/index.ts",
    "src/feedback/progress/index.ts",
    "src/feedback/skeleton/index.ts",
    "src/feedback/spinner/index.ts",
    "src/feedback/toast/index.ts",
    "src/forms/calendar/index.ts",
    "src/forms/checkbox/index.ts",
    "src/forms/combobox/index.ts",
    "src/forms/date-picker/index.ts",
    "src/forms/form-field/index.ts",
    "src/forms/input/index.ts",
    "src/forms/radio/index.ts",
    "src/forms/select/index.ts",
    "src/forms/slider/index.ts",
    "src/forms/switch/index.ts",
    "src/forms/textarea/index.ts",
    "src/layout/app-shell/index.ts",
    "src/layout/divider/index.ts",
    "src/layout/paper/index.ts",
    "src/navigation/accordion/index.ts",
    "src/navigation/breadcrumbs/index.ts",
    "src/navigation/menu/index.ts",
    "src/navigation/pagination/index.ts",
    "src/navigation/stepper/index.ts",
    "src/navigation/tabs/index.ts",
    "src/overlays/alert-dialog/index.ts",
    "src/overlays/command-palette/index.ts",
    "src/overlays/dialog/index.ts",
    "src/overlays/drawer/index.ts",
    "src/overlays/popover/index.ts",
    "src/overlays/tooltip/index.ts",
    "src/primitives/box/index.ts",
    "src/primitives/container/index.ts",
    "src/primitives/flex/index.ts",
    "src/primitives/grid/index.ts",
    "src/primitives/heading/index.ts",
    "src/primitives/stack/index.ts",
    "src/primitives/text/index.ts",
    "src/typography/link/index.ts"
  ],
  external: [
    "react",
    "react-dom",
    "react/jsx-runtime",
    "@base-ui/react",
    "react-day-picker",
    "@zed-ui/hooks",
    "@zed-ui/icons",
    "@zed-ui/system",
    "@zed-ui/themes",
    "@zed-ui/utils"
  ],
  format: ["esm", "cjs"],
  sourcemap: true,
  splitting: false,
  treeshake: true
});
