export {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableColumn,
  TableColumnGroup,
  TableColumnHeader,
  TableFooter,
  TableHead,
  TableHeader,
  TableHeaderCell,
  TableParts,
  TableRoot,
  TableRow,
  TableScrollArea,
  type TableBodyOwnProps,
  type TableCaptionOwnProps,
  type TableCaptionSide,
  type TableCellOwnProps,
  type TableColumnGroupOwnProps,
  type TableColumnOwnProps,
  type TableFooterOwnProps,
  type TableHeadOwnProps,
  type TableHeaderOwnProps,
  type TableOwnProps,
  type TableRootOwnProps,
  type TableRowOwnProps,
  type TableScrollAreaOwnProps,
  type TableSize,
  type TableVariant
} from "./Table";
